service: aws-lambda-lab

frameworkVersion: ">=1.28.0 <2.0.0"

custom:
  stage: ${opt:stage, self:provider.stage}
  # Set the table name here so we can use it while testing locally
  tableName: ${self:custom.stage}-notes
  # Set our DynamoDB throughput for prod and all other non-prod stages.
  tableThroughputs:
    prod: 5
    default: 1
  tableThroughput: ${self:custom.tableThroughputs.${self:custom.stage}, self:custom.tableThroughputs.default}

provider:
  name: aws
  runtime: go1.x
  versionFunctions: false
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "Fn::GetAtt": [ NotesTable, Arn ]
  # you can define service wide environment variables here
  environment:
    tableName: ${self:custom.tableName}

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  createNote:
    handler: bin/createnote
    events:
      - http:
          path: createnote
          method: post
          cors: true
          authorizer: aws_iam

resources:
   - ${file(resources/dynamodb-table.yml)}
